# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6a8db1d750cd685dc613ab9efc38cadd6bf06790481517a12f957b49b902b6e063c91daa087df3c0578a3aad0ed4fac5922b60f108187d736b4f4557fb610a8c

test:
  secret_key_base: 312d908a20a232d7f2303185fa0e745c75bf23ed948323c60b149789bb4ba98f96745e279eefbe522bd53b7ee7fc8dd716d41b4ff4731e4195d1fd70d3a2f4a1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
